language: ruby
rvm:
  - 2.0
  - 2.1
  - 2.2
  - rbx-2
env: "RUBY_THREAD_VM_STACK_SIZE=2097152"
script: "ruby bin/shen_test_suite.rb"
matrix:
  include:
    - rvm: jruby-1.7.17
      script: "ruby -J-Xss16m bin/shen_test_suite.rb"
